version: "2"
services:

  # OPA
  opa:
    image: openpolicyagent/opa:0.36.1
    ports:
      - "8181:8181"
    environment:
      - OTEL_GRPC_ENDPOINT=otel-collector:4317
    volumes:
      - ./opa/config.yaml:/etc/config.yaml
      - ./opa/policy/:/etc/policy/
    command: 
      - "run"
      - "-s"
      - "-c"
      - "/etc/config.yaml"
      - "-b"
      - "/etc/policy"
    depends_on:
    - otel-collector

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: ${OTEL_IMAGE}
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  go-client:
    build:
      dockerfile: Dockerfile
      context: ./go-client
    environment:
      - SERVER_ENDPOINT=http://go-server:7080
    depends_on:
      - go-server
      - otel-collector

  go-server:
    build:
      dockerfile: Dockerfile
      context: ./go-server
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OPA_ENDPOINT=http://opa:8080
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
      - opa